my_list = [1, 2, 3]
my_list.append(1)
my_list.append(2)
my_list.append(1)
my_list.append(2)
my_list.append(1)
my_list.append(2)
my_list.append(1)
my_list.append(2)
print(my_list)
print(my_list.count(1))
print(my_list.index(1))
print(my_list.index(2))
print(my_list.index(1, 2))
print(my_list.index(1, 4, 5))