print(False and False)
print(False and True)
print(True and False)
print(True and True)
print()
print(False or False)
print(False or True)
print(True or False)
print(True or True)
print()
print(not False)
print(not True)

